sudo: required
dist: trusty
language: php
php:
  - "7.2"
  - "7.1"

services:
  - docker

before_script:
  - docker pull composer
  - docker run --rm -v $(pwd):/app composer install --prefer-source --no-interaction
install:
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
  - cat Dockerfile
  - docker-compose build --build-arg PHP_VERSION=${TRAVIS_PHP_VERSION}

script:
  - docker-compose up --exit-code-from php
