sudo: required
dist: trusty
language: php
php:
  - "7.2"
  - "7.1"

services:
  - docker

install:
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
  - sed -i -e "s/php:cli/php:${TRAVIS_PHP_VERSION}-cli/g" Dockerfile
  - cat Dockerfile
  - docker-compose build

script:
  - docker-compose up --exit-code-from php
