language: php

branches:
  only:
    - master

php:
  - 5.3
  - 5.4
  - 5.5

services: mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e 'create database phpunit;'
  - composer self-update
  - composer install --dev --no-interaction

script: phpunit
