name: CI

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3]
    steps:
    - uses: actions/checkout@v1
    - name: Show php version
      run: php${{ matrix.php }} -v && composer -V
    - name: Show docker and docker-compose versions
      run: |
        docker version
        docker-compose version
    - name: Debug if needed
      run: |
        export DEBUG=${DEBUG:-false}
        if [[ "$DEBUG" == "true" ]]; then
          env
        fi
      env:
        DEBUG: ${{secrets.DEBUG}}
    - name: Install dependencies
      run: |
        docker-compose run --rm tests composer install --no-interaction
    - name: Generating code coverage
      run: |
        mkdir -p build/logs
        docker-compose run --rm tests ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
        chmod -R 0777 build/logs
    - name: Send coveralls
      run: |
        ls -alt
        composer global require cedx/coveralls
        coveralls build/logs/clover.xml
      env:
        COVERALLS_RUN_LOCALLY: 1
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
