name: CI

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3]
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
      mysql:
        image: mysql:5.7
        ports:
          - 3307:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: 'unittest'
          MYSQL_ROOT_PASSWORD:

    steps:
    - uses: actions/checkout@v1
    - name: Show php version
      run: php${{ matrix.php }} -v && composer -V
    - name: Show docker and docker-compose versions
      run: |
        docker version
    - name: Debug if needed
      run: if [[ "$DEBUG" == "true" ]]; then env; fi
      env:
        DEBUG: ${{secrets.DEBUG}}
    - name: Install dependencies
      run: |
        composer install --no-interaction
    - name: Generating code coverage
      run: |
        mkdir -p build/logs
        ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      env:
        MONGO_HOST: 0.0.0.0
        MYSQL_HOST: 0.0.0.0
        MYSQL_PORT: 3307
    - name: Send coveralls
      run: |
        export PATH="$PATH:~/.composer/vendor/bin/"
        php-coveralls build/logs/clover.xml -v
      env:
        # COVERALLS_RUN_LOCALLY: 1
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
